package tsfront

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oisee/abapiti/hir"
	"github.com/oisee/abapiti/hir/abap"
	"github.com/oisee/abapiti/tsfront/overrides"
)

// Expected observations are generated by tools/registry-features-oracle.mjs
// from the pinned original TypeScript compiler, independently of the emitter.
func TestEmitRegistryIterators(t *testing.T) {
	dir := t.TempDir()
	raw, err := os.ReadFile("testdata/registryfeatures/iterators.ts")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "iterators.ts"), raw, 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "tsconfig.json"), []byte(`{"compilerOptions":{"strict":true},"files":["iterators.ts"]}`), 0600); err != nil {
		t.Fatal(err)
	}
	p, err := Load(filepath.Join(dir, "tsconfig.json"))
	if err != nil {
		t.Fatal(err)
	}
	element := hir.Type{Kind: hir.InterfaceRef, Name: "iterators.ts.IObject"}
	registry, err := overrides.New(
		overrides.Entry{ID: "objects-fixture", Key: overrides.Key{File: "iterators.ts", Symbol: "SnapshotRegistry.getObjects", Kind: "KindMethodDeclaration"}, SHA256: "928e784e4feb5154ec9d10531182e3092908fc02d096a304a7bf5df17b61f463", Rationale: "same snapshot builder as Registry", Method: func() *hir.Method { return overrides.ObjectSnapshotMethod("iterators.ts.SnapshotRegistry", element) }},
		overrides.Entry{ID: "type-fixture", Key: overrides.Key{File: "iterators.ts", Symbol: "SnapshotRegistry.getObjectsByType", Kind: "KindMethodDeclaration"}, SHA256: "63a3e04635848a4ec1d1f0cb5b6decdc3a5390b68803c82f490b748461977dc5", Rationale: "same type snapshot builder as Registry", Method: func() *hir.Method {
			return overrides.ObjectTypeSnapshotMethod("iterators.ts.SnapshotRegistry", element)
		}},
		overrides.Entry{ID: "definitions-fixture", Key: overrides.Key{File: "iterators.ts", Symbol: "Definitions.getAll", Kind: "KindMethodDeclaration"}, SHA256: "128d2178f37e463e61975f316532af1815547442acdc38c353aa409a53a10017", Rationale: "same immutable map snapshot builder as MethodDefinitions", Method: func() *hir.Method { return overrides.DefinitionSnapshotMethod("iterators.ts.Definitions", element) }},
		overrides.Entry{ID: "files-trap-fixture", Key: overrides.Key{File: "iterators.ts", Symbol: "SnapshotRegistry.getFiles", Kind: "KindMethodDeclaration"}, SHA256: "346ca2a8b7dbf330d7231740f66b39340a91197a575f52df60155dfcaed2da2f", Rationale: "located unreached generator trap", Method: func() *hir.Method {
			return &hir.Method{Name: "getFiles", Virtual: true, Result: hir.T(hir.Array, element), Body: hir.B(&hir.Stmt{Kind: hir.Trap, Name: "iterators.ts:24"})}
		}},
	)
	if err != nil {
		t.Fatal(err)
	}
	prog, diags, err := p.LowerWithReachability([]string{"iterators.ts"}, registry, nil)
	if err != nil {
		t.Fatal(err)
	}
	if hasBlocking(diags) {
		t.Fatal(diags)
	}
	if errs := hir.Verify(prog); len(errs) > 0 {
		t.Fatal(errs, hir.Dump(prog))
	}
	t.Run("Go", func(t *testing.T) { goRegistryOracle(t, prog, "iterators", "IteratorProbe") })
	files, names, err := abap.EmitNamed(prog)
	if err != nil {
		t.Fatal(err)
	}
	raw, err = os.ReadFile("testdata/registryfeatures/iterators-oracle.json")
	if err != nil {
		t.Fatal(err)
	}
	var oracle map[string]string
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatal(err)
	}
	class := names.Get("iterators.ts.IteratorProbe")
	driver := "CLASS ltcl_iterators DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS.\nPRIVATE SECTION.\n"
	for _, method := range []string{"run"} {
		driver += fmt.Sprintf("METHODS %s FOR TESTING.\n", method)
	}
	driver += "ENDCLASS.\nCLASS ltcl_iterators IMPLEMENTATION.\n"
	for _, method := range []string{"run"} {
		expected, ok := oracle[method]
		if !ok {
			t.Fatal("missing original observation", method)
		}
		driver += fmt.Sprintf("METHOD %s.\nDATA text TYPE string.\nDATA ch TYPE c LENGTH 1.\nDATA actual TYPE string.\n", method)
		for _, s := range abapStringBuild("text", "ch", expected) {
			driver += s + "\n"
		}
		driver += fmt.Sprintf("actual = %s=>%s( ).\ncl_abap_unit_assert=>assert_equals( act = actual exp = text ).\nDATA(probe) = NEW %s( ).\ncl_abap_unit_assert=>assert_true( xsdbool( probe IS INSTANCE OF %s ) ).\nENDMETHOD.\n", class, names.Get("member."+method), class, class)
	}
	driver += "ENDCLASS.\n"
	driver = strings.Replace(driver, "METHODS run FOR TESTING.", "METHODS run FOR TESTING.\nMETHODS trap FOR TESTING.", 1)
	driver = strings.TrimSuffix(driver, "ENDCLASS.\n") + fmt.Sprintf("METHOD trap.\nDATA caught TYPE abap_bool.\nDATA exception TYPE REF TO %s.\nDATA(registry) = NEW %s( ).\nTRY.\nDATA(values) = registry->%s( ).\nCATCH %s INTO exception.\ncaught = abap_true.\nENDTRY.\ncl_abap_unit_assert=>assert_true( caught ).\ncl_abap_unit_assert=>assert_equals( act = exception->source_location exp = `iterators.ts:24` ).\nENDMETHOD.\nENDCLASS.\n", names.Get("exception.unexecuted"), names.Get("iterators.ts.SnapshotRegistry"), names.Get("member.getFiles"), names.Get("exception.unexecuted"))
	files[class+".clas.testclasses.abap"] = driver
	if out := os.Getenv("ABAPITI_TEST_OUT"); out != "" {
		if err := os.MkdirAll(out, 0755); err != nil {
			t.Fatal(err)
		}
		for name, content := range files {
			if err := os.WriteFile(filepath.Join(out, name), []byte(content), 0644); err != nil {
				t.Fatal(err)
			}
		}
	}
	t.Logf("%d emitted files", len(files))
}
