package tsfront

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/oisee/abapiti/hir"
	"github.com/oisee/abapiti/hir/abap"
)

// Expected observations are generated by tools/registry-features-oracle.mjs
// from the pinned original TypeScript compiler, independently of the emitter.
func TestEmitRegistryArrays(t *testing.T) {
	dir := t.TempDir()
	raw, err := os.ReadFile("testdata/registryfeatures/arrays.ts")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "arrays.ts"), raw, 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "tsconfig.json"), []byte(`{"compilerOptions":{"strict":true},"files":["arrays.ts"]}`), 0600); err != nil {
		t.Fatal(err)
	}
	p, err := Load(filepath.Join(dir, "tsconfig.json"))
	if err != nil {
		t.Fatal(err)
	}
	prog, diags, err := p.LowerWithReachability([]string{"arrays.ts"}, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if hasBlocking(diags) {
		t.Fatal(diags)
	}
	if errs := hir.Verify(prog); len(errs) > 0 {
		t.Fatal(errs, hir.Dump(prog))
	}
	files, names, err := abap.EmitNamed(prog)
	if err != nil {
		t.Fatal(err)
	}
	raw, err = os.ReadFile("testdata/registryfeatures/arrays-oracle.json")
	if err != nil {
		t.Fatal(err)
	}
	var oracle map[string]string
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatal(err)
	}
	class := names.Get("arrays.ts.ArrayProbe")
	driver := "CLASS ltcl_arrays DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS.\nPRIVATE SECTION.\n"
	for _, method := range []string{"shift", "optionalIndex", "staticCollections"} {
		driver += fmt.Sprintf("METHODS %s FOR TESTING.\n", method)
	}
	driver += "ENDCLASS.\nCLASS ltcl_arrays IMPLEMENTATION.\n"
	for _, method := range []string{"shift", "optionalIndex", "staticCollections"} {
		expected, ok := oracle[method]
		if !ok {
			t.Fatal("missing original observation", method)
		}
		driver += fmt.Sprintf("METHOD %s.\nDATA text TYPE string.\nDATA ch TYPE c LENGTH 1.\nDATA actual TYPE string.\n", method)
		for _, s := range abapStringBuild("text", "ch", expected) {
			driver += s + "\n"
		}
		driver += fmt.Sprintf("actual = %s=>%s( ).\ncl_abap_unit_assert=>assert_equals( act = actual exp = text ).\nDATA(probe) = NEW %s( ).\ncl_abap_unit_assert=>assert_true( xsdbool( probe IS INSTANCE OF %s ) ).\nENDMETHOD.\n", class, names.Get("member."+method), class, class)
	}
	driver += "ENDCLASS.\n"
	files[class+".clas.testclasses.abap"] = driver
	if out := os.Getenv("ABAPITI_TEST_OUT"); out != "" {
		if err := os.MkdirAll(out, 0755); err != nil {
			t.Fatal(err)
		}
		for name, content := range files {
			if err := os.WriteFile(filepath.Join(out, name), []byte(content), 0644); err != nil {
				t.Fatal(err)
			}
		}
	}
	t.Logf("%d emitted files", len(files))
}
