; Proof only. Inputs are complete, context-sensitive effect summaries, not
; optimistic summaries inferred from the absence of writes. See README.md.
(rule edge 0 (head (p_edge ?m ?n ?s))
 (base (p_call ?m ?n ?s))
 (base (p_virtual ?m ?s) (p_target ?s ?n)))
(rule resolved 0 (head (p_resolved ?s)) (base (p_target ?s _)))
(rule reach 0 (head (p_reach ?l ?m))
 (base (p_loop ?l ?m))
 (tail (p_reach ?l ?caller) (p_edge ?caller ?m _) (p_method ?m)))
(rule missing-target 0 (head (p_block ?l ?m unknown-target))
 (base (p_reach ?l ?m) (p_edge ?m ?n _) (not (p_method ?n))))
(rule incomplete 0 (head (p_block ?l ?m incomplete-effects))
 (base (p_reach ?l ?m) (not (p_complete ?m))))
(rule unknown 0 (head (p_block ?l ?m unknown-effect))
 (base (p_reach ?l ?m) (p_unknown ?m)))
(rule unresolved 0 (head (p_block ?l ?m unknown-receiver))
 (base (p_reach ?l ?m) (p_virtual ?m ?s) (not (p_resolved ?s)))
 (base (p_reach ?l ?m) (p_virtual ?m ?s) (not (p_dispatch_complete ?s))))

; A pure function can still read mutable state, return fresh identity, or throw.
; These obligations strengthen the old memo_shape + pure classification.
(rule memo 0 (head (p_memo_write ?l ?m ?r))
 (base (p_reach ?l ?m) (p_memo ?m ?r ?compute) (p_pure ?compute)
       (p_edge ?m ?compute _) (p_complete ?compute)
       (p_key_complete ?m ?r) (p_value_semantic ?m ?r)
       (p_no_invalidation ?l ?r)))
(rule counter 0 (head (p_counter_write ?l ?m ?r))
 (base (p_reach ?l ?m) (p_exact_counter ?m ?r)
       (p_counter_unobserved ?l ?r)))
(rule allowed-write 0 (head (p_allowed_write ?l ?m ?r ?kind))
 (base (p_reach ?l ?m) (p_write ?m ?r ?kind) (p_owned ?l ?r)))
(rule allowed-memo-write 0 (head (p_allowed_write ?l ?m ?r memo))
 (base (p_write ?m ?r memo) (p_memo_write ?l ?m ?r)))
(rule allowed-counter-write 0 (head (p_allowed_write ?l ?m ?r counter))
 (base (p_write ?m ?r counter) (p_counter_write ?l ?m ?r)))
(rule allowed-append-write 0 (head (p_allowed_write ?l ?m ?r append))
 (base (p_reach ?l ?m) (p_write ?m ?r append) (p_ordered_plan ?l ?r)))
(rule bad-write 0 (head (p_block ?l ?m ?r))
 (base (p_reach ?l ?m) (p_write ?m ?r ?kind)
       (not (p_allowed_write ?l ?m ?r ?kind))))
(rule written 0 (head (p_written ?l ?r))
 (base (p_reach ?l ?m) (p_write ?m ?r _)))
(rule not-memo 0 (head (p_not_memo ?l ?r))
 (base (p_reach ?l ?m) (p_write ?m ?r ?kind) (neq ?kind memo))
 (base (p_reach ?l ?m) (p_write ?m ?r memo) (not (p_memo_write ?l ?m ?r))))
(rule memo-read 0 (head (p_allowed_read ?l ?m ?r))
 (base (p_reach ?l ?m) (p_memo_read ?m ?r) (p_written ?l ?r)
       (not (p_not_memo ?l ?r))))
(rule read-conflict 0 (head (p_block ?l ?m ?r))
 (base (p_reach ?l ?m) (p_read ?m ?r) (p_written ?l ?r)
       (not (p_owned ?l ?r)) (not (p_allowed_read ?l ?m ?r))))

; An initialization edge is conditional on its guard: its body is excluded
; only with a dominance proof or a named, mandatory warm-up precondition.
(rule initialized 0 (head (p_initialized ?l ?c))
 (base (p_warmed ?l ?c)) (base (p_warm_plan ?l ?c)))
(rule cold 0 (head (p_block ?l ?m ?c))
 (base (p_reach ?l ?m) (p_init ?m ?c) (not (p_initialized ?l ?c))))
(rule warm-condition 0 (head (parallel_precondition ?l warm ?c))
 (base (p_reach ?l ?m) (p_init ?m ?c) (p_warm_plan ?l ?c)
       (not (p_warmed ?l ?c))))
(rule append-condition 0 (head (parallel_precondition ?l ordered-join ?r))
 (base (p_reach ?l ?m) (p_write ?m ?r append) (p_ordered_plan ?l ?r)))
(rule memo-condition 0 (head (parallel_precondition ?l coherent-memo ?r))
 (base (p_write ?m ?r memo) (p_memo_write ?l ?m ?r)))
(rule counter-condition 0 (head (parallel_precondition ?l atomic-counter ?r))
 (base (p_write ?m ?r counter) (p_counter_write ?l ?m ?r)))

(rule throwing 0 (head (p_throwing ?l))
 (base (p_reach ?l ?m) (p_throw ?m)))
; Counter updates are visible even when the increment result is unused.
; Memo stores are unobservable only under the value-semantic cache contract.
(rule visible 0 (head (p_visible_loop ?l ?m))
 (base (p_reach ?l ?m) (p_visible ?m))
 (base (p_reach ?l ?m) (p_write ?m _ counter)))
(rule throwing-visible 0 (head (p_block ?l ?m effect-before-throw))
 (base (p_throwing ?l) (p_visible_loop ?l ?m)))
(rule missing-exception-join 0 (head (p_block ?l ?m exception-join))
 (base (p_reach ?l ?m) (p_throw ?m) (not (p_exception_plan ?l))))
(rule exception-condition 0 (head (parallel_precondition ?l lowest-index-exception join))
 (base (p_throwing ?l) (p_exception_plan ?l)))
(rule blocked 0 (head (p_blocked ?l)) (base (p_block ?l _ _)))
(rule mark-parallel 0 (head (mark_parallel ?l))
 (base (p_loop ?l ?m) (p_method ?m) (p_isolated ?l)
       (p_slot_plan ?l) (not (p_blocked ?l))))
(rule slot-condition 0 (head (parallel_precondition ?l source-order-slots join))
 (base (mark_parallel ?l)))

(rule missing-loop-contract 0 (head (p_block ?l ?m ownership-contract))
 (base (p_loop ?l ?m) (not (p_isolated ?l))))
(rule missing-slot-contract 0 (head (p_block ?l ?m result-slot-contract))
 (base (p_loop ?l ?m) (not (p_slot_plan ?l))))
(rule missing-entry 0 (head (p_block ?l ?m unknown-entry))
 (base (p_loop ?l ?m) (not (p_method ?m))))
; I/O, progress, or publication is never an iteration-private write. The sole
; permitted visible shared update is a certified counter, handled above.
(rule external-effect 0 (head (p_block ?l ?m external-effect))
 (base (p_reach ?l ?m) (p_visible ?m)))
