// abapgit-pack: create abapGit-compatible ZIP from ABAP source files
//
// Usage:
//
//	abapgit-pack -dir ./src -mask "*.abap" -package $TMP -o output.zip
//	abapgit-pack -file program.abap -name ZPROG -desc "My program" -package $TMP -o output.zip
package main

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

type options struct {
	dir, file, mask, name, desc, pkg string
}

type object struct {
	name, kind string
	sources    map[string]string
}

func main() {
	var opts options
	flag.StringVar(&opts.dir, "dir", "", "Directory with .abap files")
	flag.StringVar(&opts.file, "file", "", "Single .abap file")
	flag.StringVar(&opts.mask, "mask", "*.abap", "File mask for directory mode")
	flag.StringVar(&opts.name, "name", "", "Object name (auto-detected from filename if empty)")
	flag.StringVar(&opts.desc, "desc", "Generated by llvm2abap", "Description")
	flag.StringVar(&opts.pkg, "package", "$TMP", "SAP package")
	output := flag.String("o", "output.zip", "Output ZIP file")
	flag.Parse()
	if err := run(opts, *output); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}

func run(opts options, output string) error {
	objects, err := readObjects(opts)
	if err != nil {
		return err
	}
	f, err := os.Create(output)
	if err != nil {
		return err
	}
	err = writeArchive(f, objects, opts.desc)
	closeErr := f.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	fmt.Printf("Created %s with %d objects\n", output, len(objects))
	return nil
}

// Namespaced abapGit filenames encode the namespace slashes as #.
var objectNamePattern = regexp.MustCompile(`^([A-Za-z][A-Za-z0-9_]*|#[A-Za-z0-9_]+#[A-Za-z][A-Za-z0-9_]*)$`)

func sourceName(filename string) (name, kind, include string, err error) {
	base := strings.ToLower(filepath.Base(filename))
	parts := strings.Split(base, ".")
	if len(parts) == 2 && parts[1] == "abap" {
		return parts[0], "prog", "", nil
	}
	if len(parts) == 3 && parts[2] == "abap" {
		switch parts[1] {
		case "clas", "intf", "prog":
			return parts[0], parts[1], "", nil
		}
	}
	if len(parts) == 4 && parts[1] == "clas" && parts[3] == "abap" {
		switch parts[2] {
		case "testclasses", "locals_imp", "locals_def", "macros":
			return parts[0], "clas", parts[2], nil
		}
	}
	return "", "", "", fmt.Errorf("unsupported ABAP source filename %q", filepath.Base(filename))
}

func readObjects(opts options) ([]object, error) {
	if opts.file == "" && opts.dir == "" {
		return nil, fmt.Errorf("use -file prog.abap or -dir ./src")
	}
	var files []string
	if opts.file != "" {
		files = append(files, opts.file)
	}
	if opts.dir != "" {
		matches, err := filepath.Glob(filepath.Join(opts.dir, opts.mask))
		if err != nil {
			return nil, fmt.Errorf("globbing sources: %w", err)
		}
		files = append(files, matches...)
	}
	objects := make(map[string]*object)
	for _, file := range files {
		name, kind, include, err := sourceName(file)
		if err != nil {
			return nil, err
		}
		if file == opts.file && opts.name != "" {
			name = strings.ToLower(opts.name)
		}
		if len(name) > 30 || !objectNamePattern.MatchString(name) {
			return nil, fmt.Errorf("invalid object name %q: use at most 30 characters, letters, digits and underscores, starting with a letter (or #namespace#name)", name)
		}
		source, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", file, err)
		}
		key := name + "." + kind
		obj := objects[key]
		if obj == nil {
			obj = &object{name: strings.ToUpper(strings.ReplaceAll(name, "#", "/")), kind: kind, sources: make(map[string]string)}
			objects[key] = obj
		}
		suffix := ".abap"
		if include != "" {
			suffix = "." + include + suffix
		}
		path := "src/" + key + suffix
		if _, exists := obj.sources[path]; exists {
			return nil, fmt.Errorf("duplicate source %s", path)
		}
		obj.sources[path] = string(source)
	}
	if len(objects) == 0 {
		return nil, fmt.Errorf("no files found")
	}
	keys := make([]string, 0, len(objects))
	for key := range objects {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	result := make([]object, 0, len(keys))
	for _, key := range keys {
		obj := objects[key]
		if _, exists := obj.sources["src/"+key+".abap"]; !exists {
			return nil, fmt.Errorf("class include requires main source %s.abap", key)
		}
		result = append(result, *obj)
	}
	return result, nil
}

func escapeXML(s string) string {
	var b bytes.Buffer
	xml.EscapeText(&b, []byte(s))
	return b.String()
}

func objectXML(obj object, desc string) string {
	name, description := escapeXML(obj.name), escapeXML(desc)
	if obj.kind == "prog" {
		descLen := len(desc)
		if descLen > 70 {
			descLen = 70
		}
		return fmt.Sprintf(programXML, name, description, descLen)
	}
	var body string
	if obj.kind == "clas" {
		body = fmt.Sprintf(`   <VSEOCLASS>
    <CLSNAME>%s</CLSNAME>
    <LANGU>E</LANGU>
    <DESCRIPT>%s</DESCRIPT>
    <STATE>1</STATE>
    <CLSCCINCL>X</CLSCCINCL>
    <FIXPT>X</FIXPT>
    <UNICODE>X</UNICODE>
`, name, description)
		for path := range obj.sources {
			if strings.HasSuffix(path, ".clas.testclasses.abap") {
				body += "    <WITH_UNIT_TESTS>X</WITH_UNIT_TESTS>\n"
				break
			}
		}
		body += "   </VSEOCLASS>\n"
	} else {
		body = fmt.Sprintf(`   <VSEOINTERF>
    <CLSNAME>%s</CLSNAME>
    <LANGU>E</LANGU>
    <DESCRIPT>%s</DESCRIPT>
    <EXPOSURE>2</EXPOSURE>
    <STATE>1</STATE>
    <UNICODE>X</UNICODE>
   </VSEOINTERF>
`, name, description)
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_%s" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
%s  </asx:values>
 </asx:abap>
</abapGit>
`, strings.ToUpper(obj.kind), body)
}

func writeArchive(dst io.Writer, objects []object, desc string) error {
	files := map[string]string{
		".abapgit.xml":         repositoryXML,
		"src/package.devc.xml": fmt.Sprintf(packageXML, escapeXML(desc)),
	}
	for _, obj := range objects {
		for path, source := range obj.sources {
			if _, exists := files[path]; exists {
				return fmt.Errorf("duplicate archive entry %s", path)
			}
			files[path] = source
		}
		name := strings.ToLower(strings.ReplaceAll(obj.name, "/", "#"))
		files["src/"+name+"."+obj.kind+".xml"] = objectXML(obj, desc)
	}
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	w := zip.NewWriter(dst)
	for _, path := range paths {
		header := &zip.FileHeader{Name: path, Method: zip.Deflate}
		header.SetModTime(time.Date(1980, time.January, 1, 0, 0, 0, 0, time.UTC))
		f, err := w.CreateHeader(header)
		if err != nil {
			return err
		}
		if _, err := io.WriteString(f, files[path]); err != nil {
			return err
		}
	}
	return w.Close()
}

const repositoryXML = `<?xml version="1.0" encoding="utf-8"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <DATA>
   <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
   <STARTING_FOLDER>/src/</STARTING_FOLDER>
   <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
   <IGNORE>
    <item>/.gitignore</item>
    <item>/LICENSE</item>
    <item>/README.md</item>
   </IGNORE>
  </DATA>
 </asx:values>
</asx:abap>
`

const packageXML = `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_DEVC" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DEVC>
    <CTEXT>%s</CTEXT>
   </DEVC>
  </asx:values>
 </asx:abap>
</abapGit>
`

const programXML = `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_PROG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <PROGDIR>
    <NAME>%s</NAME>
    <SUBC>1</SUBC>
    <RSTAT>K</RSTAT>
    <FIXPT>X</FIXPT>
    <UCCHECK>X</UCCHECK>
   </PROGDIR>
   <TPOOL>
    <item>
     <ID>R</ID>
     <ENTRY>%s</ENTRY>
     <LENGTH>%d</LENGTH>
    </item>
   </TPOOL>
  </asx:values>
 </asx:abap>
</abapGit>
`
