package wasm

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"
)

// osdCase is one call of an exported WASM function. The expected value is not
// written here: it is computed by running the same .wasm in wazero, so the
// generated ABAP Unit test checks the ABAP against an independent engine.
type osdCase struct {
	fn   string
	args []int32
}

// osdModules are the M1 modules deployed to open-steamgate. Inputs whose i32
// result wraps (add(max,1), factorial(13)) are left out: the generated ABAP
// does not wrap yet, and a kernel raises CX_SY_ARITHMETIC_OVERFLOW there.
var osdModules = []struct {
	file  string
	class string
	cases []osdCase
}{
	{"add.wasm", "zcl_abapiti_add", []osdCase{
		{"add", []int32{2, 3}},
		{"add", []int32{0, 0}},
		{"add", []int32{-1, 1}},
		{"add", []int32{-5, -7}},
		{"add", []int32{2147483647, 0}},
	}},
	{"factorial.wasm", "zcl_abapiti_factorial", []osdCase{
		{"factorial", []int32{0}},
		{"factorial", []int32{1}},
		{"factorial", []int32{5}},
		{"factorial", []int32{10}},
		{"factorial", []int32{12}},
	}},
}

// wazeroResults runs each case through wazero and returns the i32 results.
func wazeroResults(t *testing.T, bin []byte, cases []osdCase) []int32 {
	t.Helper()
	ctx := context.Background()
	rt := wazero.NewRuntime(ctx)
	defer rt.Close(ctx)
	mod, err := rt.Instantiate(ctx, bin)
	if err != nil {
		t.Fatalf("wazero instantiate: %v", err)
	}
	out := make([]int32, len(cases))
	for i, c := range cases {
		fn := mod.ExportedFunction(c.fn)
		if fn == nil {
			t.Fatalf("%s not exported", c.fn)
		}
		args := make([]uint64, len(c.args))
		for j, a := range c.args {
			args[j] = api.EncodeI32(a)
		}
		res, err := fn.Call(ctx, args...)
		if err != nil {
			t.Fatalf("wazero %s%v: %v", c.fn, c.args, err)
		}
		out[i] = api.DecodeI32(res[0])
	}
	return out
}

// osdTestClass renders the ABAP Unit local test class (ABAP 7.02) for a
// generated class: one test method per case.
func osdTestClass(class string, cases []osdCase, want []int32) string {
	var sb strings.Builder
	sb.WriteString("* Generated by wasm/osd_unit_test.go. Expected values come from wazero.\n")
	sb.WriteString("CLASS ltcl_wasm DEFINITION FINAL FOR TESTING\n")
	sb.WriteString("  DURATION SHORT RISK LEVEL HARMLESS.\n")
	sb.WriteString("  PRIVATE SECTION.\n")
	for i := range cases {
		fmt.Fprintf(&sb, "    METHODS c%d FOR TESTING.\n", i+1)
	}
	sb.WriteString("ENDCLASS.\n\n")
	sb.WriteString("CLASS ltcl_wasm IMPLEMENTATION.\n")
	for i, c := range cases {
		params := make([]string, len(c.args))
		shown := make([]string, len(c.args))
		for j, a := range c.args {
			params[j] = fmt.Sprintf("p%d = %d", j, a)
			shown[j] = fmt.Sprint(a)
		}
		label := fmt.Sprintf("%s(%s)", c.fn, strings.Join(shown, ","))
		fmt.Fprintf(&sb, "  METHOD c%d.\n", i+1)
		fmt.Fprintf(&sb, "    DATA lo TYPE REF TO %s.\n", class)
		sb.WriteString("    DATA lv_act TYPE i.\n")
		sb.WriteString("    DATA lv_exp TYPE i.\n")
		sb.WriteString("    CREATE OBJECT lo.\n")
		fmt.Fprintf(&sb, "    lv_act = lo->%s( %s ).\n", c.fn, strings.Join(params, " "))
		fmt.Fprintf(&sb, "    lv_exp = %d.\n", want[i])
		fmt.Fprintf(&sb, "    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = '%s' ).\n", label)
		sb.WriteString("  ENDMETHOD.\n")
	}
	sb.WriteString("ENDCLASS.\n")
	return sb.String()
}

// TestOSD_EmitUnitClasses compiles the M1 modules and writes, per module, the
// class and its ABAP Unit test class in abapGit file layout. The OSD workflow
// sets ABAPITI_TEST_OUT, deploys the files and runs the tests.
func TestOSD_EmitUnitClasses(t *testing.T) {
	dir := testOutDir(t)
	for _, m := range osdModules {
		bin, err := os.ReadFile(filepath.Join("testdata", m.file))
		if err != nil {
			t.Fatalf("read %s: %v", m.file, err)
		}
		mod, err := Parse(bin)
		if err != nil {
			t.Fatalf("parse %s: %v", m.file, err)
		}
		want := wazeroResults(t, bin, m.cases)
		src := Compile(mod, m.class)
		tests := osdTestClass(m.class, m.cases, want)
		checkTestClass(t, m.class, tests, want)
		for name, body := range map[string]string{
			m.class + ".clas.abap":             src,
			m.class + ".clas.testclasses.abap": tests,
		} {
			if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		t.Logf("%s: %d cases, expected %v", m.class, len(m.cases), want)
	}
}

var (
	reTestMethod = regexp.MustCompile(`(?m)^    METHODS c\d+ FOR TESTING\.$`)
	reExpected   = regexp.MustCompile(`(?m)^    lv_exp = (-?\d+)\.$`)
	reAssert     = regexp.MustCompile(`(?m)^    cl_abap_unit_assert=>assert_equals\( act = lv_act exp = lv_exp `)
)

// checkTestClass reads the generated test class back and fails unless it has
// one test method, one expected literal and one assertion per case, and the
// literals are the wazero results in order. It keeps the generated tests from
// becoming vacuous (an expected value copied from the actual one, or no
// methods at all), which OSD alone would report as green.
func checkTestClass(t *testing.T, class, src string, want []int32) {
	t.Helper()
	if len(want) == 0 {
		t.Fatalf("%s: no cases", class)
	}
	if n := len(reTestMethod.FindAllString(src, -1)); n != len(want) {
		t.Fatalf("%s: %d test methods, want %d", class, n, len(want))
	}
	if n := len(reAssert.FindAllString(src, -1)); n != len(want) {
		t.Fatalf("%s: %d assertions, want %d", class, n, len(want))
	}
	got := reExpected.FindAllStringSubmatch(src, -1)
	if len(got) != len(want) {
		t.Fatalf("%s: %d expected literals, want %d", class, len(got), len(want))
	}
	for i, g := range got {
		v, err := strconv.ParseInt(g[1], 10, 32)
		if err != nil || int32(v) != want[i] {
			t.Fatalf("%s: case %d expects %s, wazero says %d", class, i+1, g[1], want[i])
		}
	}
}
