package overrides

// Private singleton construction only assigns undefined instance data; pin the base too.
func registryStaticSingletons() []Entry {
	return []Entry{
		{ID: "abaplint-static-singleton-CGenericType", Key: Key{"src/abap/types/basic/cgeneric_type.ts", "CGenericType", "KindClassDeclaration"}, SHA256: "ff480ac0ec0099dc3acd0440b2345319a430fc5f08f873e15d60d5dd71bcfb4b", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{StaticInitializers: map[string]bool{"new CGenericType()": true}}},
		{ID: "abaplint-static-singleton-CLikeType", Key: Key{"src/abap/types/basic/clike_type.ts", "CLikeType", "KindClassDeclaration"}, SHA256: "1b652ea8e57ef7a21e99ede71c8a6662264a70b21a29b7b7db4e430fdb06f4b6", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{StaticInitializers: map[string]bool{"new CLikeType()": true}}},
		{ID: "abaplint-static-singleton-PGenericType", Key: Key{"src/abap/types/basic/pgeneric_type.ts", "PGenericType", "KindClassDeclaration"}, SHA256: "47b5b82056a381e8e67ab28bd2186b688b90b6c92e6cdb053cd4884ca752db40", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{StaticInitializers: map[string]bool{"new PGenericType()": true}}},
		{ID: "abaplint-static-singleton-SimpleType", Key: Key{"src/abap/types/basic/simple_type.ts", "SimpleType", "KindClassDeclaration"}, SHA256: "4f4f1b34891b0a94056cea10e70314bcb15a80b2a070d269831d7e682fbde059", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{StaticInitializers: map[string]bool{"new SimpleType()": true}}},
		{ID: "abaplint-static-singleton-XGenericType", Key: Key{"src/abap/types/basic/xgeneric_type.ts", "XGenericType", "KindClassDeclaration"}, SHA256: "1b9e84df599612c861a1b31ea41fabdcc9f50be8b23d94cefa8814590a4e6c11", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{StaticInitializers: map[string]bool{"new XGenericType()": true}}},
		{ID: "abaplint-static-singleton-AbstractType", Key: Key{"src/abap/types/basic/_abstract_type.ts", "AbstractType", "KindClassDeclaration"}, SHA256: "9c7a89d7a1982510fc3dfe51c304486d55a831377a23b291fe85e5e80ca22b02", Rationale: "private readonly singleton: no-arg constructor only calls pinned AbstractType constructor, which assigns undefined data; no external state or back-edge; timing unobservable, identity preserved; generalise later", Patterns: &Patterns{SourceGuard: true}},
	}
}
