package overrides

func registryMatchTests() []Entry {
	return []Entry{
		{ID: "abaplint-match-test-AllowedObjectNaming", Key: Key{"src/rules/allowed_object_naming.ts", "AllowedObjectNaming", "KindClassDeclaration"}, SHA256: "dd02bfe531dae8fa2c0343f0f86dcf90b235a818994b5eab8a472701fd09eb20", Rationale: "match array is consumed only as null test or truth value; first-match boolean is equivalent, receiver evaluated first; no capture or array escapes, regexp state is unobserved in reached five-object domain; generalise later", Patterns: &Patterns{MatchTests: map[string]bool{`name.match(allowed.customRegex)`: true, `name.match(NAME_REGEX)`: true}}},
		{ID: "abaplint-match-test-SuperclassFinal", Key: Key{"src/rules/superclass_final.ts", "SuperclassFinal", "KindClassDeclaration"}, SHA256: "f3c95b7b8a96b0e443248b6fcd355547953bee993909d0525e6b04bb5b0f9c10", Rationale: "match array is consumed only as null test or truth value; first-match boolean is equivalent, receiver evaluated first; no capture or array escapes, regexp state is unobserved in reached five-object domain; generalise later", Patterns: &Patterns{MatchTests: map[string]bool{`file.getFilename().match(/\.clas\.abap$/)`: true}}},
		{ID: "abaplint-match-test-SkipLogic", Key: Key{"src/skip_logic.ts", "SkipLogic", "KindClassDeclaration"}, SHA256: "ea46bc102304179ad216e44c3d1c74456674442e56231ba46c6cb4b37f55b389", Rationale: "match array is consumed only as null test or truth value; first-match boolean is equivalent, receiver evaluated first; no capture or array escapes, regexp state is unobserved in reached five-object domain; generalise later", Patterns: &Patterns{MatchTests: map[string]bool{`obj.getName().match(/_MPC$/i)`: true, `obj.getName().match(/_DPC$/i)`: true}}},
		{ID: "abaplint-match-test-IncludeGraph", Key: Key{"src/utils/include_graph.ts", "IncludeGraph", "KindClassDeclaration"}, SHA256: "0e927750e691ef0cd5d317f772729fce6088c46d491d821a27f582ea12159e5c", Rationale: "match array is consumed only as null test or truth value; first-match boolean is equivalent, receiver evaluated first; no capture or array escapes, regexp state is unobserved in reached five-object domain; generalise later", Patterns: &Patterns{MatchTests: map[string]bool{`name.match(FMXXINCLUDE)`: true}}},
	}
}
