; Closed-world hierarchy, dispatch, and allocation/assignment narrowing.
(rule subtype 0 (head (subtype ?c ?b))
 (base (class ?c) (extends ?c ?b))
 (base (class ?c) (implements ?c ?b))
 (tail (extends ?c ?x) (subtype ?x ?b))
 (tail (subtype ?c ?i) (interface_subtype ?i ?b)))
(rule self-type 0 (head (subtype ?c ?c)) (base (class ?c)))
(rule receivers 0 (head (receivers ?s ?c))
 (base (virtual_call ?m _ _ ?s) (exact_receiver ?s ?c))
 (base (virtual_call ?m _ _ ?s) (site_type ?s ?t) (subtype ?c ?t)
       (concrete ?c) (not (narrowed ?s))))
(rule virtual-target 0 (head (calls ?m ?n ?s))
 (base (virtual_call ?m _ ?name ?s) (receivers ?s ?c) (dispatch ?c ?name ?n)))
; Empty closed-world dispatch is uncertainty, never a purity proof.
(rule resolved 0 (head (resolved ?s)) (base (calls _ _ ?s)))
(rule unknown-virtual 0 (head (unknown_effect ?m))
 (base (virtual_call ?m _ _ ?s) (not (resolved ?s))))
(rule unknown-throw 0 (head (raises ?m ?s))
 (base (virtual_call ?m _ _ ?s) (not (resolved ?s))))
; Runtime raising is selected from reviewed adapter effects, including SpecialOps.
(rule runtime-raise 0 (head (raises ?m ?s))
 (base (runtime_op ?s ?op) (site_method ?s ?m) (op_may_raise ?op ?kind)
       (neq ?kind None)))
(rule may-throw 0 (head (may_throw ?m))
 (base (throws ?m _)) (base (trap ?m)) (base (raises ?m _))
 (tail (calls ?m ?n _) (may_throw ?n)))
(rule escape 0 (head (escapes ?m ?v))
 (base (sink ?m ?v)))
(rule escape-flow 0 (head (escapes ?m ?u))
 (base (flow ?m ?v ?u) (escapes ?m ?v)))
(rule escape-call 0 (head (escapes ?m ?v))
 (base (calls ?m ?n ?s) (argument ?s ?i ?v) (param ?n ?i ?p) (escapes ?n ?p)))
(rule escape-unknown 0 (head (escapes ?m ?v))
 (base (virtual_call ?m _ _ ?s) (not (resolved ?s)) (argument ?s _ ?v)))
(rule static-alias 0 (head (static_origin ?v ?c ?f))
 (base (flow _ ?v ?u) (static_origin ?u ?c ?f)))
(rule field-alias 0 (head (field_origin ?v ?c ?f))
 (base (flow _ ?v ?u) (field_origin ?u ?c ?f)))
(rule static-mutation 0 (head (writes_static ?m ?c ?f))
 (base (mutation ?m ?v) (static_origin ?v ?c ?f)))
(rule field-mutation 0 (head (writes_field ?m ?c ?f))
 (base (mutation ?m ?v) (field_origin ?v ?c ?f)))
(rule confined 0 (head (confined ?m ?v))
 (base (fresh ?m ?v) (not (escapes ?m ?v))))
(rule impurity 0 (head (impure ?m))
 (base (writes_field ?m _ _)) (base (writes_static ?m _ _))
 (base (mutation ?m ?v) (not (confined ?m ?v)))
 (base (unknown_effect ?m))
 (tail (calls ?m ?n _) (impure ?n)))
(rule pure 0 (head (pure ?m)) (base (defined ?m) (not (impure ?m))))
(rule static-transitive 0 (head (writes_static_transitive ?m ?c ?f))
 (base (writes_static ?m ?c ?f))
 (tail (calls ?m ?n _) (writes_static_transitive ?n ?c ?f)))
(rule memo-store 0 (head (memo_store ?m ?c ?f))
 (base (memo_shape ?m ?c ?f ?compute) (pure ?compute)))
(rule lazy-init 0 (head (lazy_init ?c))
 (base (implicit_init ?c)) (base (flag_init ?c _)))

(rule counter 0 (head (counter_store ?m ?c ?f))
 (base (counter_shape ?m ?c ?f) (not (noncounter_write ?m ?c ?f))))

; Reference bindings share escape status in both directions.
(rule escape-alias 0 (head (escapes ?m ?a))
 (base (alias ?m ?a ?b) (escapes ?m ?b))
 (base (alias ?m ?b ?a) (escapes ?m ?b)))
