; Source audit bound to archive SHA-256 in main.go. See docs/grace-parallel.md.
; Names ending ::* conservatively aggregate ALL methods of that receiver class.
(fact p_loop lexer-files lexer-map)
(fact p_method lexer-map) (fact p_complete lexer-map)
(fact p_isolated lexer-files) (fact p_slot_plan lexer-files)
(fact p_owned lexer-files lexer-graph)
(fact p_write lexer-map lexer-graph store)
(fact p_call lexer-map Lexer::* new-and-run)
(fact p_method Lexer::*) (fact p_complete Lexer::*)
(fact p_write Lexer::* lexer-graph store)
(fact p_read Lexer::* lexer-graph)
(fact p_read Lexer::* character-sets)
(fact p_init Lexer::* lexer-closure-initializers)
(fact p_warm_plan lexer-files lexer-closure-initializers)
(fact p_call Lexer::* LexerStream::* stream)
(fact p_call Lexer::* LexerBuffer::* buffer)
(fact p_call Lexer::* Token::* tokens)
(fact p_call Lexer::* Position::* position)
(fact p_virtual Lexer::* file-getRaw)
(fact p_dispatch_complete file-getRaw)
(fact p_target file-getRaw MemoryFile::getRaw)
(fact p_target file-getRaw ABAPFile::getRaw)
(fact p_method MemoryFile::getRaw) (fact p_complete MemoryFile::getRaw)
(fact p_read MemoryFile::getRaw input-raw)
(fact p_method ABAPFile::getRaw) (fact p_complete ABAPFile::getRaw)
; ABAPFile forwards to its wrapped IFile. Its reachable getRaw targets must obey
; the same closed-world input contract, recursively (no cyclic wrappers).
(fact p_virtual ABAPFile::getRaw wrapped-getRaw)
(fact p_dispatch_complete wrapped-getRaw)
(fact p_target wrapped-getRaw MemoryFile::getRaw)
(fact p_target wrapped-getRaw ABAPFile::getRaw)
(fact p_method LexerStream::*) (fact p_complete LexerStream::*)
(fact p_write LexerStream::* lexer-graph store)
(fact p_read LexerStream::* lexer-graph)
(fact p_method LexerBuffer::*) (fact p_complete LexerBuffer::*)
(fact p_write LexerBuffer::* lexer-graph store)
(fact p_read LexerBuffer::* lexer-graph)
(fact p_method Token::*) (fact p_complete Token::*)
(fact p_write Token::* lexer-graph store)
(fact p_read Token::* lexer-graph)
(fact p_call Token::* Position::* token-position)
(fact p_method Position::*) (fact p_complete Position::*)
(fact p_write Position::* lexer-graph store)
(fact p_read Position::* lexer-graph)
; Potential runtime traps are conservative. No iteration effects are published.
(fact p_throw Lexer::*) (fact p_exception_plan lexer-files)
(fact parallel_precondition lexer-files closed-inputs MemoryFile-or-acyclic-ABAPFile)
(fact parallel_precondition lexer-files immutable-inputs raw-and-character-sets)

; Negative candidates need only one decisive witness. They deliberately lack
; complete effect/ownership certificates, so removing the witness proves nothing.
(fact p_loop registry-objects Registry::parsePrivate)
(fact p_method Registry::parsePrivate)
(fact p_call Registry::parsePrivate Combi::run parse-object-statements)
(fact p_method Combi::run)
(fact p_write Combi::run Combi.release store)
(fact p_write Combi::run Combi.langVer store)
(fact p_read Combi::run Combi.release)
(fact p_read Combi::run Combi.langVer)
(fact p_loop statement-discovery StatementParser::run-first-loop)
(fact p_method StatementParser::run-first-loop)
(fact p_call StatementParser::run-first-loop ExpandMacros::find macros-find)
(fact p_method ExpandMacros::find)
(fact p_write ExpandMacros::find Macros.macros store)
(fact p_read ExpandMacros::find Macros.macros)
(fact p_call StatementParser::run-first-loop Combi::run categorize-match)
(fact p_loop statement-expansion StatementParser::run-second-loop)
(fact p_method StatementParser::run-second-loop)
(fact p_call StatementParser::run-second-loop ExpandMacros::handleMacros handle)
(fact p_method ExpandMacros::handleMacros)
(fact p_write ExpandMacros::handleMacros MacroReferences.references append)
(fact p_read ExpandMacros::handleMacros MacroReferences.references)
(fact p_call ExpandMacros::handleMacros Combi::run recursive-statement-parser)
(fact p_loop structure-files ABAPParser::parse-structure-loop)
(fact p_method ABAPParser::parse-structure-loop)
(fact p_write ABAPParser::parse-structure-loop output append)
(fact p_write ABAPParser::parse-structure-loop issues append)
(fact p_ordered_plan structure-files output)
(fact p_ordered_plan structure-files issues)
(fact p_call ABAPParser::parse-structure-loop StructureParser::runFile structure)
(fact p_method StructureParser::runFile)
(fact p_write StructureParser::runFile StructureParser.singletons store)
(fact p_call StructureParser::runFile Alternative::setupMap matcher)
(fact p_method Alternative::setupMap)
(fact p_write Alternative::setupMap Alternative.map store)
(fact p_loop syntax-objects SyntaxLogic::run)
(fact p_method SyntaxLogic::run)
(fact p_write SyntaxLogic::run object.syntaxResult store)
(fact p_call SyntaxLogic::run CurrentScope::findTypePoolType syntax-type-pool)
(fact p_method CurrentScope::findTypePoolType)
(fact p_call CurrentScope::findTypePoolType SyntaxLogic::run other-object-syntax)
(fact p_read CurrentScope::findTypePoolType object.syntaxResult)
(fact p_loop rule-objects RulesRunner::rules-iteration)
(fact p_method RulesRunner::rules-iteration)
(fact p_write RulesRunner::rules-iteration issues append)
(fact p_ordered_plan rule-objects issues)
(fact p_write RulesRunner::rules-iteration rulePerformance store)
(fact p_read RulesRunner::rules-iteration rulePerformance)
(fact p_call RulesRunner::rules-iteration UnusedVariables::run shared-rule-receiver)
(fact p_method UnusedVariables::run)
(fact p_write UnusedVariables::run UnusedVariables.workarea store)
