#!/bin/bash
set -euo pipefail

# Sync Microsoft typescript-go internal packages for the abapiti tsfront
# front end (Program + type checker only: no formatter, no language service,
# no LSP). Modelled on ramune's scripts/sync-tsgo.sh.
#
# Copies the closure of internal packages reachable from compiler/tsoptions/
# bundled/vfs into internal/tsgo and rewrites import paths:
#   github.com/microsoft/typescript-go/internal/...  ->  github.com/oisee/abapiti/internal/tsgo/...
#
# The commit is pinned below (the commit ramune pins). Set TSGO_SRC to an
# existing clone to avoid the network; its HEAD must match the pin.

TSGO_COMMIT=2bd066d87f5bafd315be9f40889d0a60b9e58e0b
TSGO_REPO=https://github.com/microsoft/typescript-go

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DST="$ROOT_DIR/internal/tsgo"

OLD_MODULE="github.com/microsoft/typescript-go/internal"
NEW_MODULE="github.com/oisee/abapiti/internal/tsgo"

# Packages needed to build a Program from a tsconfig and run the checker
# (transitive closure over non-test imports of the roots; computed with
# the script in this directory). Sorted; grouped for readability.
PACKAGES=(
    # roots: program, tsconfig parsing, bundled libs, host file systems
    compiler
    tsoptions
    bundled
    vfs
    vfs/cachedvfs
    vfs/internal
    vfs/osvfs
    vfs/vfsmatch
    # language layer
    ast
    scanner
    parser
    binder
    checker
    astnav
    evaluator
    pseudochecker
    nodebuilder
    printer
    # checker/compiler support
    core
    collections
    debug
    diagnostics
    glob
    jsnum
    json
    locale
    module
    modulespecifiers
    nativepath
    outputpaths
    packagejson
    repo
    semver
    sourcemap
    stringutil
    symlinks
    tracing
    tspath
    # pulled in by compiler (emit machinery lives in the same package)
    transformers
    transformers/declarations
    transformers/estransforms
    transformers/inliners
    transformers/jsxtransforms
    transformers/moduletransforms
    transformers/tstransforms
)

# Embedded data directories (referenced by go:embed in their packages).
DATA_DIRS=(
    bundled/libs
    diagnostics/loc
)

SRC="${TSGO_SRC:-}"
if [ -z "$SRC" ]; then
    tmp="$(mktemp -d)"
    SRC="$tmp/typescript-go"
    echo "Cloning $TSGO_REPO at $TSGO_COMMIT into $tmp ..."
    git clone --quiet --depth 1 "$TSGO_REPO" "$SRC"
    (cd "$SRC" && git fetch --quiet --depth 1 origin "$TSGO_COMMIT" && git checkout --quiet "$TSGO_COMMIT")
fi

head="$(git -C "$SRC" rev-parse HEAD)"
if [ "$head" != "$TSGO_COMMIT" ]; then
    echo "ERROR: $SRC is at $head, expected $TSGO_COMMIT" >&2
    exit 1
fi
if [ -n "$(git -C "$SRC" status --porcelain)" ]; then
    echo "ERROR: $SRC is dirty (local modifications or untracked files);" >&2
    echo "       a tree like that would not be reproducible from the pin. Use a clean checkout of $TSGO_COMMIT." >&2
    exit 1
fi
SRC_INT="$SRC/internal"
if [ ! -d "$SRC_INT/ast" ]; then
    echo "ERROR: $SRC_INT not found" >&2
    exit 1
fi

echo "Syncing typescript-go $TSGO_COMMIT packages into $DST ..."
rm -rf "$DST"

# Copy non-test .go files and other regular files (json data, ...).
for pkg in "${PACKAGES[@]}"; do
    src_dir="$SRC_INT/$pkg"
    dst_dir="$DST/$pkg"
    if [ ! -d "$src_dir" ]; then
        echo "ERROR: $src_dir not found" >&2
        exit 1
    fi
    mkdir -p "$dst_dir"
    for f in "$src_dir"/*; do
        [ -f "$f" ] || continue
        case "$(basename "$f")" in
            *_test.go) continue ;;
        esac
        cp "$f" "$dst_dir/"
    done
done

# Copy embedded data directories.
for dir in "${DATA_DIRS[@]}"; do
    if [ -d "$SRC_INT/$dir" ]; then
        mkdir -p "$DST/$(dirname "$dir")"
        cp -r "$SRC_INT/$dir" "$DST/$dir"
    else
        echo "ERROR: embedded data dir $SRC_INT/$dir not found" >&2
        exit 1
    fi
done

# Rewrite import paths in all copied .go files.
find "$DST" -name '*.go' -print0 | xargs -0 sed -i "s|\"$OLD_MODULE/|\"$NEW_MODULE/|g"

# Licence files (Apache-2.0; NOTICE.txt carries additional attributions).
cp "$SRC/LICENSE" "$DST/LICENSE"
for notice in NOTICE NOTICE.txt ThirdPartyNotices.txt; do
    if [ -f "$SRC/$notice" ]; then
        cp "$SRC/$notice" "$DST/$notice"
    fi
done

cat > "$DST/README.md" <<EOF
Copy of the \`internal/\` packages of https://github.com/microsoft/typescript-go
at commit $TSGO_COMMIT, licensed under the Apache
License 2.0 (LICENSE, NOTICE.txt). Generated by \`tools/sync-tsgo.sh\`; the only
change is the rewrite of Go import paths to \`github.com/oisee/abapiti/internal/tsgo\`.
Do not edit by hand: change the pin in the script and run it again.
EOF

go_files="$(find "$DST" -name '*.go' | wc -l | tr -d ' ')"
size="$(du -sm "$DST" | cut -f1)"
echo "Synced ${#PACKAGES[@]} packages, $go_files Go files, ${size} MB to $DST"
echo "Run 'go mod tidy' to resolve external dependencies."
